you_app/challenges/routes.py
"""Module & package import."""
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    flash,
)
from flask_login import current_user, login_required
from you_app import db
from you_app.models import Challenges
from you_app.main.utils import save_image

challenge = Blueprint("challenge", __name__)


@challenge.route("/challenges", methods=["GET", "POST"])
@login_required
def challenges():
    """Show user available and current challenges."""
    if request.method == "POST":
        title = request.form.get("title")
        dates = request.form.get("dates")
        image_file = save_image(request.files.get("image"), 1024, "assets")
        new_challenge = Challenges(title=title, dates=dates, image=image_file)
        db.session.add(new_challenge)
        db.session.commit()
        return redirect(url_for("challenge.challenges"))
    new_challenges = Challenges.query.filter_by(completed=False).all()
    completed_challenges = Challenges.query.filter_by(completed=True).all()

    context = {
        "new_challenges": new_challenges,
        "completed_challenges": completed_challenges,
    }
    return render_template("challenges.html", **context)


@challenge.route("/join-challenge", methods=["POST"])
@login_required
def join_challenge():
    """Add challenge to user's challenges."""
    challenge_id = request.form.get("challenge-id")
    challenge = Challenges.query.filter_by(id=challenge_id).first()
    if challenge.users:
        challenge.users.append(current_user)
        db.session.commit()
    if current_user.challenges:
        current_user.challenges.append(challenge)
        db.session.commit()
    else:
        current_user.challenges = [challenge]
        challenge.users = [current_user]
        db.session.commit()
    flash("Challenge joined!")
    return redirect(url_for("challenge.challenges"))

you_app/check_in/routes.py
"""Package & module import."""
from flask import Blueprint, request, redirect, url_for, jsonify
from flask_login import current_user, login_required
from you_app.models import Checkin, Goal
from you_app import db

check_in = Blueprint("check_in", __name__)

# Enable user to check in and add activity/intake for the day


@check_in.route("/add_check_in", methods=["POST"])
@login_required
def add_check_in():
    """Add values for daily goals."""
    category = request.form.get("checkin-category")
    amt_completed = request.form.get("goal")
    for_goal = Goal.query.filter_by(
        user_id=current_user.id, category=category
    ).first()
    for_goal.set_daily_percent_completed(amt_completed)
    check_in = Checkin(
        category=category, amt_completed=amt_completed, goal_id=for_goal.id
    )
    db.session.add(check_in)
    db.session.commit()
    return redirect(url_for("main.homepage"))


@check_in.route("/check_in")
@login_required
def get_goals():
    """Submit goal information for current user to front end."""
    goal_data = {}
    user_goals = Goal.query.filter_by(user_id=current_user.id)
    for goal in user_goals:
        goal_data[goal.id] = goal.category
    return jsonify(goal_data), 200
    if not user_goals:
        return jsonify(
            {
                "msg": """
                        Uh oh, you have to have goals set to check in!
                        Try adding some!
                        """
            }
        )

you_app/goals/routes.py
"""Package & module import."""
from datetime import datetime
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
)
from flask_login import login_required, current_user
from you_app.models import Goal
from you_app import db

goal = Blueprint("goal", __name__)

# TODO: Routes for users to add goals


@goal.route("/goals")
@login_required
def goals():
    """Show user visual representations of their goals."""
    goals = Goal.query.filter_by(user_id=current_user.id).all()
    for goal in goals:
        goal.daily_expected()
        goal.set_daily_expected_intake()
        db.session.commit()
    return render_template("goals.html", goals=goals)


@goal.route("/add_goal", methods=["POST"])
@login_required
def add_goal():
    """Add goal for current_user."""
    category = request.form.get("category")
    goal = request.form.get("goal")
    start_date = datetime.strptime(request.form.get("start-date"), "%m-%d-%Y")
    end_date = datetime.strptime(request.form.get("end-date"), "%m-%d-%Y")
    baseline = request.form.get("baseline")
    new_goal = Goal(
        category=category,
        goal=goal,
        start_date=start_date,
        end_date=end_date,
        user_baseline=baseline,
        user_id=current_user.id,
    )
    db.session.add(new_goal)
    db.session.commit()
    flash(
        "Great job! You've added a goal! You can add as many as you'd like."
    )
    return redirect(url_for("goal.goals"))


@goal.route("/edit_goal", methods=["GET", "POST"])
@login_required
def edit_goal():
    """Update user's goal."""
    if request.method == "GET":
        goals = Goal.query.filter_by(user_id=current_user.id).all()
        return render_template("edit_goal.html", goals=goals)
    elif request.method == "POST":
        goal_id = request.form.get("goal-id")
        new_goal_target = request.form.get("goal-target")
        new_start_date = datetime.strptime(
            request.form.get("start-date"), "%m-%d-%Y"
        )
        new_end_date = datetime.strptime(
            request.form.get("end-date"), "%m-%d-%Y"
        )
        goal_to_update = Goal.query.filter_by(id=goal_id).first()
        if new_goal_target != goal_to_update.goal:
            goal_to_update.goal = new_goal_target
        elif new_start_date != goal_to_update.start_date:
            goal_to_update.start_date = new_start_date
        elif new_end_date != goal_to_update.end_date:
            goal_to_update.end_date = new_end_date
        db.session.commit()
        flash("Goal successfully updated!")
        return redirect(url_for("goal.edit_goal"))


@goal.route("/delete_goal", methods=["POST"])
def delete_goal():
    """Delete goal from user goals."""
    goal_id = request.form.get("del-goal-id")
    goal_to_delete = Goal.query.filter_by(id=goal_id).first()
    db.session.delete(goal_to_delete)
    db.session.commit()
    flash("Goal deleted!")
    return redirect(url_for("goal.goals"))

you_app/main/routes.py
"""Import modules & packages."""
from flask import render_template, Blueprint
from flask_login import current_user
from you_app.models import Post, Goal

main = Blueprint("main", __name__)


@main.route("/")
def homepage():
    """Show user the homepage."""
    if current_user.is_authenticated:
        posts = Post.query.all()
        user_challenges = current_user.challenges
        news_feed = posts + user_challenges
        goals = Goal.query.filter_by(user_id=current_user.id)
        return render_template("index.html", news_feed=news_feed, goals=goals)
    else:
        return render_template("landing-page.html")

you_app/progress/routes.py
"""Package & module import."""
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from you_app.models import Goal

progress = Blueprint("progress", __name__)


@progress.route("/progress")
@login_required
def progress_page():
    """Show user current progress in challenges."""
    goals = Goal.query.filter_by(user_id=current_user.id).all()
    for goal in goals:
        goal.set_percent_completed()
    return render_template("progress.html", goals=goals)

you_app/user/routes.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from flask_login import login_user, login_required, logout_user, current_user
from you_app import db
from you_app.models import User

user = Blueprint("user", __name__)


@user.route("/login", methods=["GET", "POST"])
def login():
    """Login user."""
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if not user:
            flash("We couldn't find You! Check your email and try again.")
        elif user and user.verify_password(password):
            login_user(user)
            flash("You have successfully logged in!")
            return redirect(url_for("main.homepage"))
        elif not user.verify_password(password):
            flash("Incorrect password, please try again.")
    return render_template("login.html")


@user.route("/signup", methods=["GET", "POST"])
def register():
    """Register (sign up) new user."""
    if request.method == "POST":
        email = request.form.get("email")
        username = request.form.get("username")
        password = request.form.get("password")
        pass_confirm = request.form.get("confirm-password")
        user = User.query.filter_by(email=email).first()
        if user:
            flash(
                """
                A user already exists with that email address.
                Do you need to log in?
                """
            )
        elif password == pass_confirm:
            new_user = User(email=email, username=username)
            new_user.set_password(password)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            flash("You have successfully signed up! You are now logged in.")
            flash("What can we help You accomplish? Add your goals here!")
            return redirect(url_for("goal.goals"))
    return render_template("register.html")


@user.route("/logout")
@login_required
def logout():
    """Log out user."""
    logout_user()
    flash("You have successfully logged out!")
    return redirect(url_for("main.homepage"))


@user.route("/settings", methods=["GET", "POST"])
@login_required
def settings():
    """Allow user to edit their personal settings."""
    if request.method == "GET":
        return render_template("settings.html")
    elif request.method == "POST":
        new_username = request.form.get("username")
        new_email = request.form.get("email")
        new_password = request.form.get("password")
        new_confirm_pass = request.form.get("confirm-password")

        if (
            User.query.filter_by(username=new_username).first()
            and new_username != current_user.username
        ):
            flash("Username taken. Please try again.")
        elif (
            User.query.filter_by(email=new_email).first()
            and new_email != current_user.email
        ):
            flash("An account with that email already exists.")
        elif (
            new_confirm_pass
            and new_password
            and new_confirm_pass == new_password
        ):
            current_user.set_password(new_password)
            db.session.commit()
            flash("Your password has been updated.")
            return redirect(url_for("user.settings"))
        else:
            current_user.username = new_username
            current_user.email = new_email
            db.session.commit()
            flash("Your account has been updated!")
            return redirect(url_for("user.settings"))
        return redirect(url_for("user.settings"))

you_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> -->
  <title>You</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}" defer></script>
  <script type="text/javascript" src="{{ url_for('static', filename='js/checkin.js') }}" defer></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous" defer></script>
  {% block head %}{% endblock %}
</head>

<body>
  <header>
    <!-- MAIN NAV ELEMENTS -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
      <a class="navbar-brand navbar-item active" href="{{ url_for('main.homepage') }}">You</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('challenge.challenges') }}">Challenges</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('goal.goals') }}">Goals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('progress.progress_page') }}">Progress</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="open-checkin-modal">Check In</a>
          </li>
          {% endif %}
        </ul>
        <!-- SETTINGS DROPDOWN -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{% if current_user.is_authenticated %}<img src="{{ url_for('static', filename='assets/settings.png') }}"
              alt="Gear icon" id="settings-dropdown"></a>
          <div class="dropdown-menu">
            <a href="{{ url_for('user.settings') }}" class="dropdown-item">Settings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('user.logout') }}">Log Out</a>
            {% else %}<button type="button" class="btn btn-primary" id="settings-dropdown">Get Started!</button></a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('user.login') }}">Log In</a>
              <a class="dropdown-item" href="{{ url_for('user.register') }}">Sign Up</a>
              {% endif %}
            </div>
        </li>
        {% if current_user.is_authenticated %}
        <!-- SEARCH BAR -->
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        <!-- PROFILE IMAGE BUTTON IF LOGGED IN USER -->
        <button type="button" id="open-glance" class="img-btn"><img src="{{ url_for('static', filename='assets/default_profile_pic.jpg') }}" alt="Woman in fitness gear outside" class="profile-pic"></button>
        {% endif %}
      </div>
    </nav>
  </header>
  <!-- INITIALIZE FLASH MESSAGES -->
  <div class="row w-100">
    <div class="flash-messages col-md-6 offset-6 mr-auto ml-auto">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <p class="mb-5 text-center">{{ message }}</p>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>
    <!-- AT A GLANCE CARD -->
    <div class="glance-card p-0 invisible" id="at-a-glance">
      <div class="card mb-3">
        <h3 class="card-header">You, at a glance</h3>
        <div class="card-body">
          {% for goal in goals %}
          <h5 class="card-title">{{ goal.category }}</h5>
          <h6 class="card-subtitle text-muted">{{ goal.daily_goal_percent }}% to daily goal</h6>
          {% endfor %}
        </div>
        <div class="card-body">
          <a href="{{ url_for('progress.progress_page') }}" class="card-link">See Progress</a>
          <a href="{{ url_for('goal.goals') }}" class="card-link">Check your goals</a>
        </div>
        <div class="card-footer text-muted">
          Last updated: 1 hr ago
        </div>
      </div>
    </div>
    <!-- CHECK IN MODAL -->
    <div class="backdrop" id="checkin-modal-backdrop"></div>

    <div class="modal" id="checkin-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Check In</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true" id="x-checkin-btn">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{{ url_for('check_in.add_check_in')}}" method="POST" id="check-in-form">
              <div class="row w-100 justify-content-center">
                <div class="col-md-6">
                  <label for="checkin-category">What goal is this for?</label>
                  <select class="form-control" name="checkin-category" id="checkin-cat-select" form="check-in-form">
                    <option value="pick-one">Select One</option>
                    <option value="Water Intake">Water Intake</option>
                    <option value="Steps">Steps</option>
                    <option value="Heart Rate">Resting Heart Rate</option>
                    <option value="Calories">Calories</option>
                    <option value="Weight">Weight</option>
                  </select>
                  <div class="invisible" id="checkin-form-part-two">
                    <label for="input" id="input-label">Placeholder</label>
                    <input class="form-control" type="number" name="goal" id="goal">
                  </div>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary" id="save-checkin">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close-checkin">Close</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- SETTINGS MODAL -->

    <div class="modal" id="checkin-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Check In</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true" id="x-checkin-btn">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{{ url_for('check_in.add_check_in')}}" method="POST" id="check-in-form">
              <div class="row w-100 justify-content-center">
                <div class="col-md-6">
                  <label for="checkin-category">What goal is this for?</label>
                  <select class="form-control" name="checkin-category" id="checkin-cat-select" form="check-in-form">
                    <option value="pick-one">Select One</option>
                    <option value="Water Intake">Water Intake</option>
                    <option value="Steps">Steps</option>
                    <option value="Heart Rate">Resting Heart Rate</option>
                    <option value="Calories">Calories</option>
                    <option value="Weight">Weight</option>
                  </select>
                  <div class="invisible" id="checkin-form-part-two">
                    <label for="input" id="input-label">Placeholder</label>
                    <input class="form-control" type="number" name="goal" id="goal">
                  </div>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary" id="save-checkin">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close-checkin">Close</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block content %}{% endblock %}
  <!-- FOOTER -->
  <footer class="page-footer font-small">
    <div class="footer-copyright text-center py-3">
      © Copyright Sid Arcidiacono 2020
    </div>
  </footer>
</body>

</html>

you_app/templates/challenges.html
{% extends 'base.html' %}

{% block head %}
<script type="text/javascript" src="{{ url_for('static', filename='js/challenges.js')}}" defer></script>
{% endblock %}

{% block content %}
<div class="container-fluid p-0 w-100">

  <!-- BACKDROP FOR MODAL OPEN -->
  <div class="backdrop" id="modal-backdrop"></div>

  <!-- ADD CHALLENGE BUTTON -->
  <div class="row w-100 justify-content-center m-3">
    <div class="col-md-6 d-flex align-items-center">
      <button type="button" class="btn btn-primary m-auto" id="start-modal-btn">Add New Challenge</button>
    </div>
  </div>

  <!-- ADD CHALLENGE MODAL -->
  <div class="row w-100">
    <div class="modal" id="add-challenge-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Add a Challenge</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true" id="x-button">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{{ url_for('challenge.challenges') }}" method="POST" enctype="multipart/form-data">
              <div class="row w-100 justify-content-center">
                <div class="col-md-4">
                  <label for="title">Challenge Title</label>
                  <input class="form-control" type="text" name="title" id="title">
                </div>
                <div class="col-md-4">
                  <label for="dates">Dates</label>
                  <input class="form-control" type="text" name="dates" id="dates">
                </div>
              </div>
              <div class="col-md-4">
                <label for="image">Image</label>
                <input class="form-control" type="file" name="image" id="image">
              </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary" id="save-add-challenge">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal" id="stop-add-challenge">Close</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- ACTIVE CHALLENGE CARDS -->
{% if new_challenges or completed_challenges %}

<div class="row w-100 justify-content-center">
  <h2>Upcoming Challenges</h2>
</div>

{% for new_challenge in new_challenges %}
<div class="row w-100 justify-content-center">
  <div class="container m-3">
    <div class="row text-white bg-primary mb-3 w-100 rounded">
      <div class="col-md-4 text-left">
        <h3 class="card-title p-4">{{ new_challenge.title }}</h3>
        <p class="card-text p-4">{{ new_challenge.dates }}</p>
      </div>
      <div class="col-md-3 ml-auto mr-0 p-0 d-flex flex-row">
        <form class="d-flex flex-row h-50 mt-auto mb-auto" action="{{ url_for('challenge.join_challenge') }}" method="POST">
          <input type="hidden" name="challenge-id" value="{{ new_challenge.id }}">
          <button type="submit" id="join-challenge" class="img-btn small"><img src="{{ url_for('static', filename='assets/orange_add_plus.png') }}" alt="plus shaped button"></button>
        </form>
        <img class="challenge-img h-100" src="{{ url_for('static', filename='assets/' + new_challenge.image) }}" alt="{{ new_challenge.title }}">
      </div>
    </div>
  </div>
</div>
{% endfor %}

<!-- COMPLETED CHALLENGE CARDS -->
<div class="row justify-content-center">
  <h2>Completed Challenges</h2>
</div>

{% for completed_challenge in completed_challenges %}
<div class="row w-100 justify-content-center">
  <div class="container m-3">
    <div class="row text-white border-primary mb-3 w-100 rounded">
      <div class="col-md-4 text-left">
        <h3 class="card-title p-4">{{ new_challenge.title }}</h3>
        <p class="card-text p-4">{{ new_challenge.dates }}</p>
      </div>
      <div class="col-md-3 ml-auto mr-0 p-0">
        <img class="challenge-img h-100" src="{{ url_for('static', filename='assets/' + new_challenge.image) }}" alt="{{ new_challenge.title }}">
      </div>
    </div>
  </div>
</div>

{% endfor %}
{% else %}

<!-- DISPLAY IF THERE ARE NO CHALLENGES TO SHOW -->
<div class="row w-100 justify-content-center mt-4 mb-4">
  <h3 class="text-center">No challenges yet!</h3>
</div>

{% endif %}
</div>

{% endblock %}

you_app/templates/edit_goal.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid w-100 p-0">

  <div class="row w-100 justify-content-center m-4">
    <div class="col-md-6 justify-content-center text-center">

      <h2 class="mb-4">Update Goals</h2>
    </div>

  {% if goals %}
  {% for goal in goals %}
  <div class="row w-100 justify-content-left">
    <div class="col-md-4 mb-4">
      <div class="card text-white bg-secondary mb-3">
        <div class="card-header">{{ goal.category }}</div>
        <div class="card-body">
          {% if goal.category == "Water Intake" %}
          <h4 class="card-title">{{ goal.goal }} oz per day</h4>
          {% elif goal.category == "Steps" %}
          <h4 class="card-title">{{ goal.goal }} steps per day</h4>
          {% elif goal.category == "Heart Rate" %}
          <h4 class="card-title">{{ goal.goal }} beats per minute</h4>
          {% elif goal.category == "Calories" %}
          <h4 class="card-title">{{ goal.goal }} calories per day</h4>
          {% elif goal.category == "Weight" %}
          <h4 class="card-title">{{ goal.goal }} lbs</h4>
          {% endif %}
          <p class="card-text">You started working towards this goal on: {{ goal.start_date.strftime('%b %d, %Y') }}</p>
          <p class="card-text">You plan to achieve this goal by: {{ goal.end_date.strftime('%b %d, %Y') }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <form action="{{ url_for('goal.edit_goal') }}" method="POST">
        <input class="form-control" type="hidden" name="goal-id" value="{{ goal.id }}">
        <label class="mt-1 mb-0" for="goal-target">Goal Target</label>
        <input class="form-control" type="number" name="goal-target" id="goal-target" value="{{ goal.goal }}">
        <label class="mt-1 mb-0" for="start-date">Start Date (mm-dd-yyyy)</label>
        <input class="form-control" type="date" name="start-date" id="start-date" value="{{ goal.start_date.strftime('%m-%d-%Y') }}">
        <label class="mt-1 mb-0" for="end-date">End Date (mm-dd-yyyy)</label>
        <input class="form-control" type="date" name="end-date" id="end-date" value="{{ goal.end_date.strftime('%m-%d-%Y') }}">
    </div>
    <div class="col-md-4 m-auto">
      <input class="btn btn-secondary" type="submit" value="Update {{ goal.category }}">
    </form>
      <form action="{{ url_for('goal.delete_goal') }}" method="POST">
        <input type="hidden" name="del-goal-id" value="{{ goal.id }}">
        <button type="submit" class="btn btn-primary mt-2" name="button">Delete This Goal</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>

{% endblock %}

you_app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid p-0 w-100">

  <div class="row justify-content-center">
    <div class="col-md-6 mt-3 justify-content-center">
      <form action="{{ url_for('user.login') }}" method="POST">
        <fieldset class="justify-content-center">
          <legend>Log In</legend>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>
      </form>
      <small>Need an account? <a href="{{ url_for('user.register') }}">Sign Up</a></small>
    </div>
  </div>
</div>

{% endblock %}

you_app/templates/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid p-0 w-100">

<div class="row justify-content-center">
  <div class="col-md-6 mt-3 justify-content-center">
    <form action="{{ url_for('user.register') }}" method="POST">
      <fieldset class="justify-content-center">
        <legend>Sign Up!</legend>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control" name="username" placeholder="Username">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Confirm Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="confirm-password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </fieldset>
    </form>
    <small>Already have an account? <a href="{{ url_for('user.login') }}">Log In</a></small>
  </div>
</div>

</div>
{% endblock %}